# -*- coding: utf-8 -*-
"""DNA.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIChgn64tw7bVVMrbGJ1yhYsB2QVREyk
"""

dna=input('Enter your dna sequence:').upper()
print(dna)
for base in dna:
  if base not in 'ACTG':
    print('enter a valid DNA sequence')
    break
else:
    print('valid DNA sequence')
    t_dna=len(dna)
    print('for dna sequence:', dna)
    print(f'total dna length is {t_dna} nucleotides')
    A=dna.count('A')
    C=dna.count('C')
    G=dna.count('G')
    T=dna.count('T')
    print('adenine is:', A)
    print('cytosine is:', C)
    print('guanine is:', G)
    print('thymine is:', T)