# -*- coding: utf-8 -*-
"""GC.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_WWgF4wPmBK6he5RxKE-mxyFNqSTt3Q
"""

inp=input('Enter your dna sequence:')
dna=inp.upper()
print(dna)
for base in dna:
  if base not in 'ACTG':
    print('enter a valid DNA sequence')
    break
else:
    print('valid DNA sequence')
    t_dna=len(dna)
    print('for dna sequence:', dna)
    print(f'total dna length is {t_dna} nucleotides')
    A=dna.count('A')
    T=dna.count('T')
    G=dna.count('G')
    C=dna.count('C')
    print('adenine is:', A)
    print('thymine is:', T)
    print('guanine is:', G)
    print('cytosine is:', C)
    GC=((G+C)/t_dna)*100
    print('GC content is:', round(GC,3), '%')