# -*- coding: utf-8 -*-
"""HAMM.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMkJrdpU6gQtHTDEsU9-xgmMCY-Os-bf
"""

x=input('Enter 1st sequence:').upper()
for base in x:
  if base not in 'ACGT':
    print('Enter a VALID sequence')
    break
else:
  y=input('Enter 2nd sequence:').upper()
  for base in y:
    if base not in 'ACGT':
      print('Enter a VALID sequence')
      break #simpler loop stm't.: if any(base not in 'ACGT' for base in y):
  else:
    if len(x)!=len(y):
      print('Sequences must be the same length')
    else:
      count=0
      for i in range(len(x)):
        if x[i]!=y[i]:
          count=count + 1 #or count += 1
          #simpler stm't. counting mismatch: sum(1 for a,b in zip(x,y) if a!=b)
      print(count)