# -*- coding: utf-8 -*-
"""RECM.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15eyV0flLtONKm3axSvKosEMFunFRO7kf
"""

dna=input('Enter your dna sequence:').upper()
print(dna)
rev=dna[::-1]
print(rev)
R=''
for base in rev:
  if base == 'A':
    R += 'T'
  if base == 'C':
    R += 'G'
  if base == 'G':
    R += 'C'
  elif base == 'T':
    R += 'A'
print('Reverse complement is:', R)