# -*- coding: utf-8 -*-
"""RNA.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIChgn64tw7bVVMrbGJ1yhYsB2QVREyk
"""

dna=input('Enter your dna sequence:').upper()
print(dna)
rna=dna.replace('T','U' )
print(rna)