# -*- coding: utf-8 -*-
"""SUBS.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBH7tcAb_oemzbmrEx0YDJUQStAdjhxx
"""

s=input('Enter your sequence(s):').upper()
if any(base not in 'ACGT' for base in s):
  print('Enter a valid sequence')
else:
  t=input('Enter motif sequence(t):').upper()
  if any(base not in 'ACGT' for base in t):
      print('Enter a valid motif')
  else:
    print(s)
    print('motif:', t)
    for i in range(len(s)):
      if s[i:].startswith(t):
        print(i+1)

